### ISSUE TITLE
Geared hubs: high torque warning independent from wheel diameter

### ISSUE THREAD

**Issue by snubz** [dirkelko/gear-calculator#3]
There is a warning if one chooses a geared hub with a slow transmission ratio, e.g. Nexus Inter 7, 30T chainring, 16T sprocket. The warning should advise against chosing a transmission that is out of bounds and will destroy the geared hub eventually.
 https://www.gear-calculator.com/?GR=SNI7&KB=30&RZ=16&UF=2215&TF=90&SL=2.6&UN=KMH&DV=teeth

This error message does not take into account that the size of the wheel alters the transmission ratio too. In other words, this warning is triggered everytime the ratio of the teeth of chainring and sprocket gets smaller than 2. It does not matter which wheel diameter is chosen. But in reality there is a difference if I use a 16" wheel or a 28" wheel.

The limit that is stated in the manual (p. 10) is valid only for 26" wheels. 
https://si.shimano.com/pdfs/dm/GN0001/DM-GN0001.pdf

My proposal would be, to use the example given in the manual as starting point and calculate the corresponding metres of development. In this case, this would be 2.62 metres of development. The warning should be shown, whenever the value of metres of development is smaller than 2.62.

**Comment by dirkelko** [comment]
Thanks for the hint, but there seems to be a misunderstanding.
The limiting value to avoid damage for an internal gear hub is the torque which reaches the cog. This torque is dependent of the force the rider pushes the pedal, crank length and the ratio between chainwheel and cog but it is not dependent of the wheel size. 
Since the manufacturers of internal gear hubs don't know how strong the riders are they typically state a recommended minimal ratio between chainwheel and cog (assuming a strong and heavy rider). I am using these ratio values which are published by the manufacturers.
(The Shimano manual you state does not handle internal gear hubs)

**Comment by snubz** [comment]
That makes sense. Thank you. 

I meant to link to this document:
https://si.shimano.com/en/pdfs/dm/SG0003/DM-SG0003-08-ENG.pdf

I was irritated, because the example given (p.10) refers to a wheel diameter. But now I think, they mentioned the diameter, because they state numbers of teeth for chainwheel and sprocket.
